filebeat.inputs:
- type: filestream
  id: default-filestream
  paths:
    - ingest_data/*.log

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

processors:
- add_docker_metadata: ~

setup.kibana:
  host: http://kibana:5601
  username: elastic
  password: ${ELASTIC_PASSWORD} 

output.elasticsearch:
  hosts: http://elasticsearch:9200
  username: elastic
  password: ${ELASTIC_PASSWORD}