global:
  scrape_interval: "15s"
  scrape_timeout: "10s"

scrape_configs:
  - job_name: app
    metrics_path: /metrics
    static_configs:
      - targets: ['app-yk63.onrender.com']
    scheme: https
    
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090