version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      -  MONGO_URI=mongodb://root:example@mongo:27017/
    volumes:
      - ./app:/app

  mongo:
   image: mongo:latest
   ports:
       - 27018:27017
   environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example   
   volumes:
      - mongo_data:/data/db

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
    driver: local